name: Owen Ou's Blog
subtitle: Blog.new(:kind => "geek")

auto: true
pygments: true
permalink: /:year/:month/:day/:title

# Absolute base URL for this site without trailing slash
url: http://localhost:4000

# Absolute URL of feed.
# You may want to change this URL to point to a feedburner feed.
feed: http://localhost:4000/atom.xml

# Author element in atom feed. Optional.
# If email is supplied, name is required.
author:
  name: Jingwen Owen Ou
  email: jingweno@gmail.com



